// <auto-generated />
using System;
using HrAppApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrAppApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611014323_SeedStaffAndDepartments")]
    partial class SeedStaffAndDepartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("HrAppApi.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "General"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Information Communications Technology"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Human Resources"
                        });
                });

            modelBuilder.Entity("HrAppApi.Models.HrRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HrRequests");
                });

            modelBuilder.Entity("HrAppApi.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Javaville",
                            Country = "Australia",
                            DepartmentId = -2,
                            Name = "John Smith",
                            Phone = "02 9988 2211",
                            State = "NSW",
                            Street = "1 Code Lane",
                            Zip = "0100"
                        },
                        new
                        {
                            Id = 2,
                            City = "Byte Cove",
                            Country = "Australia",
                            DepartmentId = -3,
                            Name = "Sue White",
                            Phone = "03 8899 2255",
                            State = "QLD",
                            Street = "16 Bit Way",
                            Zip = "1101"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cloud Hills",
                            Country = "Australia",
                            DepartmentId = -4,
                            Name = "Bob O’Bits",
                            Phone = "05 7788 2255",
                            State = "VIC",
                            Street = "8 Silicon Road",
                            Zip = "1001"
                        },
                        new
                        {
                            Id = 4,
                            City = "Appletson",
                            Country = "Australia",
                            DepartmentId = -3,
                            Name = "Mary Blue",
                            Phone = "06 4455 9988",
                            State = "NT",
                            Street = "4 Processor Boulevard",
                            Zip = "1010"
                        },
                        new
                        {
                            Id = 5,
                            City = "Bufferland",
                            Country = "Australia",
                            DepartmentId = -4,
                            Name = "Mick Green",
                            Phone = "02 9988 1122",
                            State = "NSW",
                            Street = "700 Bandwidth Street",
                            Zip = "0110"
                        });
                });

            modelBuilder.Entity("HrAppApi.Models.Staff", b =>
                {
                    b.HasOne("HrAppApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
